### ISSUE TITLE
setting date above 2050 causes script errors

### ISSUE THREAD

**Issue by OhTanoshi** [rebel1324/CityRP#18]
Alrighty so we were messing with setting in the config and found out after 2050 in the date it causes a script error i will get the error  when im able to get back on gmod

**Comment by biorisk2** [comment]
I experienced issues with dates as well, when setting the year higher or lower by a decent amount, this was on hl2rp schema on 1.1.
I ended up redoing the UI to just type in the day and time, I do think this should be fixed.

**Comment by LukeCall** [comment]
I think the reason for this is you have to set the date before starting your server for the first time with the schema, when I experienced this issue with HL2RP I found this to be the issue, it's because everything sets itself up with the date from the first boot with the gamemode and doesn't like change.
